name: Slither Analysis
on: [push]

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set .env
        run: cp env.template .env

      - name: Run Slither
        uses: crytic/slither-action@v0.3.0
        with:
          fail-on: none
          sarif: results.sarif
          slither-config: slither.config.json
          slither-args: --checklist --markdown-root ${{ github.server_url }}/${{ github.repository }}/blob/${{ github.sha }}/

      - name: Push SARIF to GH
        uses: github/codeql-action/upload-sarif@v2
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: results.sarif

      - name: Push SARIF to DefectDojo
        # TODO: push to DefectDojo
        run: ls results.sarif
